import type {
  GiverBriefChecklistItem,
  GiverBroadcastQuest,
  GiverBudgetCard,
  GiverCandidate,
  GiverEscrowEntry,
  GiverKpiCard,
  GiverPostQuestInsight,
} from "./giver";

export const giverKpiCards: GiverKpiCard[] = [
  { label: "Quest Open", value: "26", hint: "8 butuh slot tambahan", tone: "bg-[#DBEAFE]" },
  { label: "Fill Rate", value: "78.4%", hint: "+3.2% vs minggu lalu", tone: "bg-[#DCFCE7]" },
  { label: "Avg Match Time", value: "12m", hint: "target <= 15m", tone: "bg-[#E9D5FF]" },
  { label: "Escrow Locked", value: "Rp8.4jt", hint: "44 quest aktif", tone: "bg-[#FEF3C7]" },
  { label: "Release Rate", value: "86.9%", hint: "dispute 2.3%", tone: "bg-[#FCE7F3]" },
];

export const giverBroadcastQuests: GiverBroadcastQuest[] = [
  {
    id: "QST-2026-0412-901",
    title: "Restock Minimarket Harian",
    status: "LIVE",
    mode: "Per-Individu",
    skillTag: "Retail + Inventory",
    wageBand: "Rp150.000 - Rp250.000",
    slotFilled: 0,
    slotTotal: 1,
    baseRadiusKm: 1,
    maxRadiusKm: 5,
    elapsedSeedSeconds: 110,
    deadline: "12 Apr 2026, 13:30",
    location: "Pasar Minggu",
    estimatedCandidates: 21,
    escrowState: "LOCKED",
  },
  {
    id: "QST-2026-0412-857",
    title: "Pickup Stok Gudang",
    status: "WAITING_RUNNER",
    mode: "Ber-Kelompok",
    skillTag: "Delivery + Heavy Lift",
    wageBand: "Rp300.000 - Rp520.000",
    slotFilled: 2,
    slotTotal: 5,
    baseRadiusKm: 1,
    maxRadiusKm: 6,
    elapsedSeedSeconds: 402,
    deadline: "12 Apr 2026, 17:00",
    location: "Kuningan",
    estimatedCandidates: 34,
    escrowState: "LOCKED",
  },
  {
    id: "QST-2026-0412-882",
    title: "Survey Display Snack UMKM",
    status: "MATCH",
    mode: "Per-Individu",
    skillTag: "Retail + Visual Merch",
    wageBand: "Rp200.000 - Rp300.000",
    slotFilled: 1,
    slotTotal: 1,
    baseRadiusKm: 1,
    maxRadiusKm: 4,
    elapsedSeedSeconds: 755,
    deadline: "12 Apr 2026, 16:00",
    location: "Depok",
    estimatedCandidates: 14,
    escrowState: "PENDING_CONFIRMATION",
  },
  {
    id: "QST-2026-0412-811",
    title: "Bersihkan Booth Event",
    status: "FROZEN",
    mode: "Ber-Kelompok",
    skillTag: "Cleaning + Event Support",
    wageBand: "Rp250.000 - Rp380.000",
    slotFilled: 3,
    slotTotal: 4,
    baseRadiusKm: 1,
    maxRadiusKm: 5,
    elapsedSeedSeconds: 1205,
    deadline: "12 Apr 2026, 20:00",
    location: "Cilandak",
    estimatedCandidates: 29,
    escrowState: "IN_PROGRESS",
  },
];

export const giverCandidates: GiverCandidate[] = [
  {
    id: "cand-neira",
    name: "Neira",
    distanceKm: 0.8,
    etaMinutes: 6,
    skill: "Cleaning + Retail",
    matchScore: 93,
    completionRate: "97.2%",
    disputeRatio: "0.8%",
    reliabilityBadge: "Fast Responder",
    status: "Ready",
  },
  {
    id: "cand-miska",
    name: "Miska",
    distanceKm: 1.6,
    etaMinutes: 11,
    skill: "Retail + Display",
    matchScore: 88,
    completionRate: "95.8%",
    disputeRatio: "1.1%",
    reliabilityBadge: "High Completion",
    status: "On Quest",
  },
  {
    id: "cand-raka",
    name: "Raka",
    distanceKm: 2.1,
    etaMinutes: 14,
    skill: "Delivery + Merchandising",
    matchScore: 82,
    completionRate: "94.9%",
    disputeRatio: "1.3%",
    reliabilityBadge: "Night Owl",
    status: "Standby",
  },
  {
    id: "cand-naufal",
    name: "Naufal",
    distanceKm: 2.4,
    etaMinutes: 16,
    skill: "Tech Assist + Retail",
    matchScore: 79,
    completionRate: "93.2%",
    disputeRatio: "1.8%",
    reliabilityBadge: "Quick Fix",
    status: "Ready",
  },
  {
    id: "cand-aghnia",
    name: "Aghnia",
    distanceKm: 3.1,
    etaMinutes: 20,
    skill: "Cleaning Pro",
    matchScore: 86,
    completionRate: "96.8%",
    disputeRatio: "0.9%",
    reliabilityBadge: "Trusted Pro",
    status: "Ready",
  },
  {
    id: "cand-farel",
    name: "Farel",
    distanceKm: 2.8,
    etaMinutes: 18,
    skill: "Survey + Pickup",
    matchScore: 77,
    completionRate: "93.7%",
    disputeRatio: "1.9%",
    reliabilityBadge: "SLA Keeper",
    status: "Standby",
  },
];

export const giverBudgetCards: GiverBudgetCard[] = [
  { label: "Budget Allocation", value: "Rp12.5jt", hint: "58% sudah dipakai", tone: "bg-[#DBEAFE]" },
  { label: "Platform Fee", value: "Rp775rb", hint: "6.2% fee blended", tone: "bg-[#DCFCE7]" },
  { label: "Pending Release", value: "Rp2.1jt", hint: "11 quest menunggu approve", tone: "bg-[#FEF3C7]" },
  { label: "Refund/Dispute Hold", value: "Rp430rb", hint: "3 kasus perlu review", tone: "bg-[#FECACA]" },
];

export const giverEscrowEntries: GiverEscrowEntry[] = [
  {
    id: "esc-001",
    questId: "QST-2026-0412-901",
    type: "LOCKED",
    amount: "Rp250.000",
    note: "Runner belum mulai tugas.",
    time: "09:01",
  },
  {
    id: "esc-002",
    questId: "QST-2026-0412-857",
    type: "PENDING_RELEASE",
    amount: "Rp520.000",
    note: "Slot runner 2/5, menunggu final group.",
    time: "11:44",
  },
  {
    id: "esc-003",
    questId: "QST-2026-0412-882",
    type: "RELEASED",
    amount: "Rp285.000",
    note: "Setelah potong fee platform.",
    time: "10:51",
  },
  {
    id: "esc-004",
    questId: "QST-2026-0411-774",
    type: "REFUND",
    amount: "Rp300.000",
    note: "Quest dibatalkan karena brief berubah.",
    time: "Kemarin 21:08",
  },
  {
    id: "esc-005",
    questId: "QST-2026-0411-741",
    type: "DISPUTE",
    amount: "Rp130.000",
    note: "Menunggu verifikasi bukti hasil.",
    time: "Kemarin 19:33",
  },
];

export const giverBriefChecklistItems: GiverBriefChecklistItem[] = [
  {
    id: "brief-skill-tag",
    label: "Skill tag jelas dan spesifik",
    description: "Gunakan tag bidang kerja agar matching runner lebih presisi.",
    weight: 20,
    required: true,
    defaultChecked: true,
  },
  {
    id: "brief-acceptance",
    label: "Acceptance criteria terukur",
    description: "Cantumkan output yang harus terpenuhi sebelum release escrow.",
    weight: 20,
    required: true,
    defaultChecked: true,
  },
  {
    id: "brief-proof",
    label: "Bukti hasil wajib (foto/file/checklist)",
    description: "Minimalkan dispute dengan format proof yang konsisten.",
    weight: 18,
    required: true,
    defaultChecked: false,
  },
  {
    id: "brief-slot",
    label: "Jumlah slot runner sesuai beban kerja",
    description: "Untuk mode kelompok, pastikan slot tidak under/over.",
    weight: 12,
    required: true,
    defaultChecked: true,
  },
  {
    id: "brief-radius",
    label: "Radius + aturan auto-expand",
    description: "Set radius awal dan ekspansi 5 menit agar fill-rate stabil.",
    weight: 15,
    required: false,
    defaultChecked: true,
  },
  {
    id: "brief-wage",
    label: "Rentang upah kompetitif",
    description: "Bandingkan dengan demand lokal untuk percepat conversion.",
    weight: 15,
    required: false,
    defaultChecked: false,
  },
];

export const giverPostQuestInsights: GiverPostQuestInsight[] = [
  {
    id: "insight-1",
    title: "Naikkan upah band untuk quest kelompok",
    recommendation: "Untuk slot 3+ runner, tambah wage minimum +12% menaikkan fill-rate hingga 16%.",
    impact: "Potential Fill Rate +16%",
    confidence: "88%",
    tone: "bg-[#DBEAFE] text-[#1D4ED8]",
  },
  {
    id: "insight-2",
    title: "Auto-expand radius setelah menit ke-10",
    recommendation: "Quest dengan demand tinggi sebaiknya ekspansi dari 1km ke 2km pada menit 10-15.",
    impact: "Match Time -3.4m",
    confidence: "84%",
    tone: "bg-[#DCFCE7] text-[#166534]",
  },
  {
    id: "insight-3",
    title: "Prioritaskan runner badge Fast Responder",
    recommendation: "Segmen retail sore hari konversi lebih stabil dengan responder < 5 menit.",
    impact: "Completion +6.1%",
    confidence: "79%",
    tone: "bg-[#E9D5FF] text-[#6D28D9]",
  },
  {
    id: "insight-4",
    title: "Kurangi dispute lewat proof format wajib",
    recommendation: "Template proof before-after menurunkan dispute ratio sampai 1.1 poin.",
    impact: "Dispute -1.1pt",
    confidence: "91%",
    tone: "bg-[#FEF3C7] text-[#92400E]",
  },
];
